services:
  postgres:
    image: postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}   
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - '3003:3003'
    environment:  
      DATABASE_URL: ${DATABASE_URL}   
    depends_on:
      - postgres
       
  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    ports: 
      - '8008:8008'
    environment:  
      DATABASE_URL: ${DATABASE_URL}   
    depends_on:
      - postgres
 
  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile.docs 
    ports: 
      - '3000:3000'
    environment:  
      DATABASE_URL: ${DATABASE_URL}    
    depends_on:
      - postgres

volumes:
  postgres-data:            
