FROM oven/bun:1 AS base

WORKDIR /app

ARG DATABASE_URL

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

RUN bun install

COPY . .

RUN bun run db:generate

RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3001

CMD ["bun","run","start:web"]