FROM oven/bun:1 AS base

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

RUN bun install

COPY . . 

RUN bun run db:generate

EXPOSE 8080

CMD ["bun","run","start:websocket"]